* Use case of BY GROUP;
* #BY GROUP#グループの最初と最後のオブザベーションの検索#FIRST.variable #LAST.variable;
proc sort data=company.usa out=work.temp;
    by dept;
run;
* 部門ごとの年間支払い料の計算;
data company.budget(keep=dept payroll);
    set work.temp;
    by dept;
    if wagecat='S' then Yearly=wagerate*12;
    else if wagecat='H' then Yearly=wagerate*2000;
    if first.dept then Payroll=0;
    payroll+yearly;
    if last.dept;
run;
* 部門ごとの年間支払給料の一覧と合計;
proc print data=company.budget noobs;
    sum payroll;
    format payroll dollar12.2;
run;